import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import Brewery from "next/font/local";
import Montserrat from "next/font/local";
import Header from "@/components/shared/Header/Header";

const montserrat = Montserrat({
  src: [
    {
      path: "../public/fonts/Montserrat-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Montserrat-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-montserrat",
});
const brewery = Brewery({
  src: "../public/fonts/Brewery No2 CYR W10 Regular.woff2",
  display: "swap",
  variable: "--font-brewery",
});
const manrope = Manrope({
  weight: ["300", "400", "500", "700"],
  subsets: ["cyrillic-ext", "cyrillic", "latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Современный магизин мебели",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`font-manrope ${brewery.variable} ${montserrat.variable} ${manrope.variable} bg-black text-white`}
      >
        <Header />
        <main className="relative z-5">{children}</main>
      </body>
    </html>
  );
}
